In [26]:
reset -fs

In [27]:
import numpy as np

<center><h2> Naive Bayes in Scikit-learn</h2></center>

In [28]:
corpus  = ["🐈 🐯 🐱 🐩 🐱", 
           "🐶 🐶 🐈 🐶 🐩 🐈 🐶 🐶", 
           "🐈 🐈 🐯 🐶 🐈",  
           "🐈 🐈 🐈",
           "🐶 🐶 🐯 🐈 🐩 🐱 🐩 🐶 🐩 🐶 "]

y = ['cat', 'dog', 'cat', 'cat','dog'] 

In [29]:
for target, item,  in zip(y, corpus):
    print(f"{target}: {item}")

cat: 🐈 🐯 🐱 🐩 🐱
dog: 🐶 🐶 🐈 🐶 🐩 🐈 🐶 🐶
cat: 🐈 🐈 🐯 🐶 🐈
cat: 🐈 🐈 🐈
dog: 🐶 🐶 🐯 🐈 🐩 🐱 🐩 🐶 🐩 🐶 


In [30]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(token_pattern=r'[^\s]+')
X = vectorizer.fit_transform(corpus)

In [31]:
# Introspect features
print(vectorizer.get_feature_names_out())
print(X.toarray())

['🐈' '🐩' '🐯' '🐱' '🐶']
[[1 1 1 2 0]
 [2 1 0 0 5]
 [3 0 1 0 1]
 [3 0 0 0 0]
 [1 3 1 1 4]]


In [32]:
from sklearn.naive_bayes import MultinomialNB

clf = MultinomialNB()
clf.fit(X, y)

MultinomialNB()

In [33]:
# Prediction on training data: "🐈 🐯 🐱 🐩 🐱"
print(clf.predict([[1, 1, 1, 2, 0]]))

['cat']


In [35]:
# Prediction on unseen data
new_input = "🐱"
# new_input = "🐱 🐩 "
# new_input = "🐱 🐩 🐩"
vectorized = vectorizer.transform([new_input])
print(clf.predict(vectorized))

['cat']


In [36]:
# Let's interpert the feature weights
print("Features - Probability", end="\n\n")
print("'cat' category:")
for feature, log_prob_ in zip(vectorizer.get_feature_names_out(), clf.feature_log_prob_[0]):
    print(f"{feature} - {np.exp(log_prob_):.3f}")

Features - Probability

'cat' category:
🐈 - 0.444
🐩 - 0.111
🐯 - 0.167
🐱 - 0.167
🐶 - 0.111


In [37]:
# Let's interpert the feature weights
print("Features - Probability", end="\n\n")
print("'dog' category:")
for feature, log_prob_ in zip(vectorizer.get_feature_names_out(), clf.feature_log_prob_[1]):
    print(f"{feature} - {np.exp(log_prob_):.3f}")

Features - Probability

'dog' category:
🐈 - 0.174
🐩 - 0.217
🐯 - 0.087
🐱 - 0.087
🐶 - 0.435


<center><img src="images/questions.png" width="65%"/></center>

<br>
<br> 
<br>

<center><h2>Sources of Inspiration</h2></center>

- https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html
- https://stackoverflow.com/questions/57333183/sk-learn-countvectorizer-keeping-emojis-as-words
- https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.MultinomialNB.html#sklearn.naive_bayes.MultinomialNB