<center><h1>Naive Bayes Introduction</h1></center>

<center><img src="images/dare_to_be_naive.jpeg" width="75%"/></center>

<center><h2>Who am I?</h2></center>
<center><img src="images/hi.png" width="37%"/></center>

<center>Brian Spiering</center>

<center>Data Science Instructor</center>

<center><h2>Agenda</h2></center>

1. Intro to machine learning
1. Naive Bayes overview 
1. Naive Bayes from scratch
1. Naive Bayes in scikit-learn
1. Questions & Answers

<center><h2>What is classification?</h2></center>

<center>Predicting a single category from a collection of discrete categories. </center> 

<center><h2>Dog or Lion?</h2></center>
<center><img src="images/prediction.png" width="50%"/></center>

<center><h2>Classification Methods</h2></center>

1. Hand-written Rules
1. Machine learning

<center><h2>Hand-written Rules</h2></center>
<br>
<br>
<center>Write a series of "if this then that" statements by hand.</center>

<center><h2>Hand-written Rules Examples</h2></center>

- If "Viagra" or "Nigerian Prince" appear, then an email is spam.

- If words such as "worst ever" and "terrible" appear in a movie review, then the review is negative.

<center><h2>What are the downsides of hand written rules?</h2></center>

1) Time intensive 

2) Brittle 

1. Time intensive 
    - Require Humans
    - To be complete, a large set of rules would be needed.

2. Brittle
    - Rules could not easily apply to new situations. Either new domains or as domains change over time

<center><h2>Machine Learning</h2></center>
<br>
<br>
<center>Automatically learn patterns from the data</center>

<center>If certain words co-occur with certain categories, let's find those relationship by writing computer code.</center>

<center><h2>Bayes Rule</h2></center>
<center><img src="images/Thomas_Bayes.png" width="100%"/></center>

<center><h2>Bayes Rule</h2></center>
<center><img src="images/bayes_with_text.jpeg" width="85%"/></center>

TODO: Put in example of using bayes rule

<center><h2>Bayes Rule as an ML algorithm</h2></center>

<center><img src="images/bayes-rule-color.png" width="75%"/></center>

<center>Evaluate our hypothesis, given our prior beliefs and new empirical evidence</center>

<center><h2>Naive Bayes for Text Classification</h2></center>

 $$p(\text{class }| \text{ doc}) = \frac{p(\text{doc } | \text{ class}) \times p(\text{class})}{p(\text{doc})}$$


$$p(\text{class }| \text{ doc}) = \frac{\boxed{p(\text{doc } | \text{ class})} \times p(\text{class})}{p(\text{doc})}$$
 
$p(\text{doc } | \text{ class})$: observing a document given a particular class (Likelihood)


 $$p(\text{class }| \text{ doc}) = \frac{p(\text{doc } | \text{ class}) \times \boxed{p(\text{class})}}{p(\text{doc})}$$
 
$p(\text{class})$: observing each of the classes (Prior)


 $$p(\text{class }| \text{ doc}) = \frac{p(\text{doc } | \text{ class}) \times p(\text{class})}{\boxed{p(\text{doc})}}$$
 
$p(\text{doc})$: observing an individual document (Marginal)

Since <b>all</b> calculated probabilities have the same $p(\text{doc})$, we can drop $p(\text{doc})$ from the denominator.

 $$\boxed{p(\text{class }| \text{ doc})} = \frac{p(\text{doc } | \text{ class}) \times p(\text{class})}{p(\text{doc})}$$
 
$p(\text{class }| \text{ doc})$: observing a particular class given a document (Posterior)


<center><h2>New document prediction </h2></center>

$$P(\text{class } |\text{ doc}) =   (P(word_1 \text{ | class}) \newline \times P(word_2 \text{ | class}) ... \times P(word_n \text{ | class})) \times P(\text{class})$$




<center><h2>New document prediction </h2></center>

$$ P(\text{class } |\text{ doc}) = \prod_{i=1}^n P(word_i | \text{class })\newline \times  P(\text{class })$$


Source: https://medium.com/@theflyingmantis/text-classification-in-nlp-naive-bayes-a606bf419f8c

<center><h2>Being Naive: <br> Bayes' Greatest Strength & Greatest Weakness</h2></center>
<center><img src="images/dare_to_be_naive.jpeg" width="50%"/></center>

<center><h2>Naive: Each word is conditionally independent for each label
</h2></center>

Naive Bayes ignores word order, aka Bag-of-Words assumption


<center>What about combinations of words? </center>
<br>
<center>For example, "not terrible" in a movie review</center>

<center><h2>Naive Bayes works in practice</h2></center>


<center><img src="images/buffet.jpeg" width="90%"/></center>

Despite feature independence assumption, Naive Bayes is very common and useful

<center><h2>Real-world applications</h2></center>

- Fraud detection 🕵️‍♀️

- Is a review positive 👍 or negative 👎?

- Medical diagnosis (➕ or ➖)?

<center><img src="images/questions.png" width="65%"/></center>

<center><h2>Implement Naive Bayes <br>From Scratch</h2></center>

<center><h2>Bayes' Theorem</h2></center>


<br>
<center><img src="images/bayes_rule.png" width="100%"/></center>

<center><h2>Training Naive Bayes</h2></center>

1. Acquire labeled data
1. Preprocess data
1. Calculate document class priors
1. Calculate word by class conditional probabilities

Acquire data & preprocess
-----

In [1]:
reset -fs

In [2]:
corpus  = ["🐈 🐯 🐱 🐩 🐱", 
           "🐶 🐶 🐈 🐶 🐩 🐈 🐶 🐶", 
           "🐈 🐈 🐯 🐶 🐈",  
           "🐈 🐈 🐈",
           "🐶 🐶 🐯 🐈 🐩 🐱 🐩 🐶 🐩 🐶 "]

labels = ['cat', 'dog', 'cat', 'cat','dog'] 

In [3]:
data = [['cat', "🐈 🐯 🐱 🐩 🐱"],
        ['dog', "🐶 🐶 🐈 🐶 🐩 🐈 🐶 🐶"],
        ['cat', "🐈 🐈 🐯 🐶 🐈"],
        ['cat', "🐈 🐈 🐈"], 
        ['dog', "🐶 🐶 🐯 🐈 🐩 🐱 🐩 🐶 🐩 🐶 "]]

In [4]:
for label, item in data:
    print(f"{label}: {item}")

cat: 🐈 🐯 🐱 🐩 🐱
dog: 🐶 🐶 🐈 🐶 🐩 🐈 🐶 🐶
cat: 🐈 🐈 🐯 🐶 🐈
cat: 🐈 🐈 🐈
dog: 🐶 🐶 🐯 🐈 🐩 🐱 🐩 🐶 🐩 🐶 


<center><h2>Calculate class priors</h2></center>

$$P(c) = \frac{N_c}{N}$$

In [5]:
# What labels are we dealing with?
labels = set(labels)
labels

{'cat', 'dog'}

In [6]:
# How many documents are dealing with?
n_docs = len(corpus)
n_docs

5

In [7]:
from collections import defaultdict

doc_priors = defaultdict(float)

In [8]:
# For each label, find the probability of baseline occurance
for label in labels:
    doc_priors[label] = sum(1 for item_label, _ in data if item_label == label) / n_docs

print(*doc_priors.items(), sep='\n')

('dog', 0.4)
('cat', 0.6)


<center><h2>Conditional probabilities of word by class</h2></center>

In [9]:
vocab = []

In [10]:
# Get all tokens, aka the vocabulary
for _, doc in data:
    vocab.extend(doc.split())
    
print("Vocab:", vocab)

Vocab: ['🐈', '🐯', '🐱', '🐩', '🐱', '🐶', '🐶', '🐈', '🐶', '🐩', '🐈', '🐶', '🐶', '🐈', '🐈', '🐯', '🐶', '🐈', '🐈', '🐈', '🐈', '🐶', '🐶', '🐯', '🐈', '🐩', '🐱', '🐩', '🐶', '🐩', '🐶']


In [11]:
# Unique tokens
set(vocab)

{'🐈', '🐩', '🐯', '🐱', '🐶'}

In [12]:
# Number of unique tokens, aka cardinality
v = len(set(vocab))
print("Cardinality of vocab:", v)

Cardinality of vocab: 5


In [13]:
# A default dict of default dicts; inner default dict is probability
cond_prob = defaultdict(lambda: defaultdict(float))

In [14]:
for label in labels:    
    label_tokens = []
    for item_label, doc in data:
        # For a given label, get a list of all the tokens for all the docs 
        if item_label == label:
            label_tokens.extend(doc.split())

    for token in vocab:
        # Find conditional probability: token count / total count
        cond_prob[label][token] = label_tokens.count(token) / len(label_tokens) 

In [15]:
for label, sub_dict in cond_prob.items():
    print(label.title(), ":")
    for token, prob in sub_dict.items():
        print(token, prob)

Dog :
🐈 0.16666666666666666
🐯 0.05555555555555555
🐱 0.05555555555555555
🐩 0.2222222222222222
🐶 0.5
Cat :
🐈 0.5384615384615384
🐯 0.15384615384615385
🐱 0.15384615384615385
🐩 0.07692307692307693
🐶 0.07692307692307693


In [16]:
# Test that each label is a probability mass function (pmf). A pmf sums to 1
from math import isclose

for label in labels:
    assert isclose(sum(cond_prob[label].values()), 1)

<center><h2>Predicting with Naive Bayes</h2></center>

1. Acquire and process the new data
1. For each new data point, calculate the proportional probabilities for each class
1. Pick the winning class

<center><h2>Given a new document, <br> calculate the proportional probabilities for each class</h2></center>

$$ P(c | X) = P(c) •  \prod_{i=1}^n P(x_i | c)$$

In [17]:
# Define product function
import operator
from functools import reduce

def product(iterable):
    return reduce(operator.mul, iterable, 1)

In [18]:
new_input = "🐱"
# new_input = "🐱 🐩 "
# new_input = "🐱 🐩 🐩"

prob_predicted = defaultdict(float)
for label in labels:
    # For each label, calculate the conditional probability based on the prior and the tokens that appear
    prob_predicted[label] = doc_priors[label] * product(cond_prob[label][t] for t in new_input.split())
    
print(*dict(prob_predicted).items(), sep='\n')

('dog', 0.022222222222222223)
('cat', 0.09230769230769231)


# Pick the winning class

In [19]:
from operator import itemgetter

In [20]:
label, prob = max(prob_predicted.items(), key=itemgetter(1))
print("The predicted class is: ", end="")
print(*(k for k, v in prob_predicted.items() if v == prob))

The predicted class is: cat


In [21]:
# Handle ties and fall back to document priors if winning probability is zero

label, prob = max(prob_predicted.items(), key=itemgetter(1))
if prob > 0:
    print("The predicted class is: ", end="")
    print(*(k for k, v in prob_predicted.items() if v == prob))
else:
    label, prob = max(doc_priors.items(),
                      key=itemgetter(1))
    print("The predicted class is:", label)

The predicted class is: cat


<center><img src="images/questions.png" width="65%"/></center>

<center><h2>Bonus Material</h2></center>

- Other implementations by Brian Spiering
    - [Using NormalDist from statistics module](https://github.com/brianspiering/naive_bayes_classifer_in_python_3_8)
    - [Naive Bayes for Text Classification](https://github.com/brianspiering/bayesian-text)
    
- [Implementation by mircealex](https://github.com/mircealex)

In [22]:
reset -fs

In [23]:
import numpy as np

<center><h2> Naive Bayes in Scikit-learn</h2></center>

In [24]:
corpus  = ["🐈 🐯 🐱 🐩 🐱", 
           "🐶 🐶 🐈 🐶 🐩 🐈 🐶 🐶", 
           "🐈 🐈 🐯 🐶 🐈",  
           "🐈 🐈 🐈",
           "🐶 🐶 🐯 🐈 🐩 🐱 🐩 🐶 🐩 🐶 "]

y = ['cat', 'dog', 'cat', 'cat','dog'] 

In [25]:
for target, item,  in zip(y, corpus):
    print(f"{target}: {item}")

cat: 🐈 🐯 🐱 🐩 🐱
dog: 🐶 🐶 🐈 🐶 🐩 🐈 🐶 🐶
cat: 🐈 🐈 🐯 🐶 🐈
cat: 🐈 🐈 🐈
dog: 🐶 🐶 🐯 🐈 🐩 🐱 🐩 🐶 🐩 🐶 


In [26]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(token_pattern=r'[^\s]+')
X = vectorizer.fit_transform(corpus)

In [27]:
# Introspect features
print(vectorizer.get_feature_names_out())
print(X.toarray())

['🐈' '🐩' '🐯' '🐱' '🐶']
[[1 1 1 2 0]
 [2 1 0 0 5]
 [3 0 1 0 1]
 [3 0 0 0 0]
 [1 3 1 1 4]]


In [28]:
from sklearn.naive_bayes import MultinomialNB

clf = MultinomialNB()
clf.fit(X, y)

MultinomialNB()

In [29]:
# Prediction on training data: "🐈 🐯 🐱 🐩 🐱"
print(clf.predict([[1, 1, 1, 2, 0]]))

['cat']


In [30]:
# Prediction on unseen data
new_input = "🐱"
# new_input = "🐱 🐩 "
# new_input = "🐱 🐩 🐩"
vectorized = vectorizer.transform([new_input])
print(clf.predict(vectorized))

['cat']


In [31]:
# Let's interpert the feature weights
print("Features - Probability", end="\n\n")
print("'cat' category:")
for feature, log_prob_ in zip(vectorizer.get_feature_names_out(), clf.feature_log_prob_[0]):
    print(f"{feature} - {np.exp(log_prob_):.3f}")

Features - Probability

'cat' category:
🐈 - 0.444
🐩 - 0.111
🐯 - 0.167
🐱 - 0.167
🐶 - 0.111


In [32]:
# Let's interpert the feature weights
print("Features - Probability", end="\n\n")
print("'dog' category:")
for feature, log_prob_ in zip(vectorizer.get_feature_names_out(), clf.feature_log_prob_[1]):
    print(f"{feature} - {np.exp(log_prob_):.3f}")

Features - Probability

'dog' category:
🐈 - 0.174
🐩 - 0.217
🐯 - 0.087
🐱 - 0.087
🐶 - 0.435


<center><img src="images/questions.png" width="65%"/></center>

<center><h2>Sources of Inspiration</h2></center>

- https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html
- https://stackoverflow.com/questions/57333183/sk-learn-countvectorizer-keeping-emojis-as-words
- https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.MultinomialNB.html#sklearn.naive_bayes.MultinomialNB

<center><h2>Naive Bayes Takeaways</h2></center>

1) Learns how features are associated with categories

2) Simply & Effective: a great choice for a baseline model


<center><h2>Naive Bayes Takeaways</h2></center>

3) Straightforward to implement


4) However, you should use scikit-learn

<center><h2>All These Materials <br> (and bonus materials)</h2></center>

[bit.ly/naive-bayes-intro](http:bit.ly/naive-bayes-intro)   
or   
[github.com/brianspiering/naive_bayes_intro](http://github.com/brianspiering/naive_bayes_intro)

 <center><img src="images/questions.png" width="65%"/></center>

<br>
<br> 
<br>

<center><h2>Bonus Material</h2></center>

<center><h2>Bayes Rule for Classification</h2></center> 

<center><img src="images/bayes_rule.png" width="100%"/></center>

<center><h2>Likelihood</h2></center>

How likely we are to observe the data point given a specific label?

<center><h2>Class Prior Probability</h2></center>

How likely we are to observe each of the label, ignoring the data?

Also called base-rate.

<center><h2>Predictor Prior Probability</h2></center>


How likely we are to observe any given data point?

In the case of text classification, probability of observing an individual document.

<center><h2>Posterior Probability</h2></center>


Predict probability of a label given a new observation.

The goal of machine learning classification.

<center><h2>In text classification features are critical</h2></center>

<center><img src="images/supervised_learning.png" width="80%"/></center>

<center><h2>What features might you want to use for text classification? </h2></center>

- Data:
    - Individual words
    - Phrases
    - Punctuation


- Metadata:
    - Length of document
    - Language
    - Sender or receiver

<center><h2>Naive Bayes "embarrassingly parallelizable"</h2></center>

Each feature weight can be learned separately for each class.

Thus it can be learned at the same time on a separate computer / core.

Source: https://alitarhini.wordpress.com/2011/03/02/parallel-naive-bayesian-classifier/

<br>
<br> 
<br>

----